### ISSUE TITLE
Insert event into multiple calendars

### ISSUE THREAD

**Issue by paulmenzel** [itchyny/calendar.vim#104]
Inserting an event, it’d be great if it could be added to several calendars, by for example passing a comma separated list of the calendar indexes.

**Comment by nicolassilvar** [comment]
The ReadMe or Wiki do not contain details on how to add an event to the calendar. Does it support it? Just curious, would love to know

**Comment by itchyny** [comment]
@nicolassilvar Just press i.

@paulmenzel Thanks for feature request, but I'm not sure how many people want the feature...
