### ISSUE TITLE
No Color in Neovim

### ISSUE THREAD

**Issue by geastwood** [itchyny/calendar.vim#109]
NVIM: 0.1.7
echo &t_Co => 256
echo $TERM => xterm-256color

<img width="1920" alt="screen shot 2017-01-02 at 22 47 28" src="https://cloud.githubusercontent.com/assets/1623359/21596606/84078976-d13d-11e6-9c36-346abfcadd58.png">

**Comment by itchyny** [comment]
I cannot reproduce this problem with the following init.vim.
```
call plug#begin()
Plug 'itchyny/calendar.vim'
call plug#end()
set background=dark
syntax on
```
