### ISSUE TITLE
ADD Proxy Config Support  for connectting calendar_google_calendar

### ISSUE THREAD

**Issue by huangming** [itchyny/calendar.vim#111]
I can‘t connect to google calendar without proxy.

**Comment by echuraev** [comment]
I'm working through proxy. And connection to Google Calendar is working now. I just set env variables: 
```bash
export http_proxy=http://my-proxy-server.com:port/
export https_proxy=https://my-proxy-server.com:port/
```
But unfortunately it works only for calendar. Google Tasks are not synced with Task list.

**Comment by xuehongzhi** [comment]
fantastic work!!！with the same issue google tasks not synced!!

**Comment by itchyny** [comment]
I believe this problem is already fixed. Please specify `HTTPS_PROXY`.
