### ISSUE TITLE
Selecting Google calendars to be displayed

### ISSUE THREAD

**Issue by isene** [itchyny/calendar.vim#114]
Absolutely awesome Vim plugin (an amazing programming feat).

Would it be possible to add the feature of selecting which Google calendars are displayed?

**Comment by itchyny** [comment]
Currently calendar.vim does not have configuration for this. You can toggle the visibility on calendar.google.com (on the left hand side) and calendar.vim will sync with it.

**Comment by isene** [comment]
I know. It would be nice to have this feature in calendar.vim as well.

**Comment by isene** [comment]
Is it possible to change thoe index order of the calendars when I create new events - especially which calendar becomes the default (0)?

**Comment by itchyny** [comment]
The index order of calendars is resolved by `g:calendar_calendar_candidates`.

**Comment by isene** [comment]
How do I set that variable?

**Comment by itchyny** [comment]
Example: `let g:calendar_calendar_candidates = ["My calendar", "Reminders", "something else"]` where the values are matched against the calendar titles. Refer to `:h g:calendar_calendar_candidates` for details.

**Comment by isene** [comment]
Great. Thanks :-)
