### ISSUE TITLE
Nicer views (replacing line characters such as | + and - )

### ISSUE THREAD

**Issue by isene** [itchyny/calendar.vim#115]
I tried to figure out where the line characters are placed in the code tree, but got lost. It would be nice to replace the regular | + and - characters that makes up the boxes in the views with the characters │┼ and ─ and possibly also ┘ ┐ ┌ └ ├ ┤ ┴ ┬ to make the lines in the boxes continuous.

**Comment by itchyny** [comment]
calendar.vim actually uses unicode borders https://github.com/itchyny/calendar.vim/blob/0d86fb4b3/autoload/calendar/setting.vim#L187
Please confirm that `:echo &enc ==# 'utf-8' && &fenc ==# 'utf-8'` prints `1`.

**Comment by isene** [comment]
That was a quick response.

It prints "0"

How to fix?

**Comment by isene** [comment]
Fixed it with:

set   fileencoding=utf-8
