### ISSUE TITLE
Calendar not refreshing after editing event on web

### ISSUE THREAD

**Issue by isene** [itchyny/calendar.vim#117]
On a day with many events, pressed "E" to see the list of events. Cursor at one specific event, pressed ENTER to bring the event up in browser. Moved the event 30 minutes in browser, closed the tab. The event in calendar.vim still displays the old time for the event. Any way to force a new sync with google?

**Comment by isene** [comment]
I can of course force a resync by creating a "dummy" event and then deleting it - but needless to say that is a cumbersome  way to force a sync :-)

**Comment by itchyny** [comment]
Currently there's no way to force a sync, but the events will be updated automatically within half an hour.

**Comment by isene** [comment]
Could you perhaps add a Resync function and make Ctrl-r its default binding?

**Comment by isene** [comment]
Having been using calendar.vim for three weeks now, I am only missing this one feature: To be able to force a resync of the calendars from Google. At the moment, I am quitting vim to restart calendar.vim to force the resync...

**Comment by AVaccNY** [comment]
+1 resync would be nice :) 

Love the app, though! Thanks.

**Comment by isene** [comment]
Could you tell me where in the code the calendar resync'ing happens? You said it would happen every half hour or so - maybe I can change the interval to a shorter time?

**Comment by itchyny** [comment]
I have implemented this feature. Please use `<C-r>` to force resync.

**Comment by isene** [comment]
yooohoooo!

**Comment by AVaccNY** [comment]
Thanks!!!

**Comment by jumbosushi** [comment]
Was looking for this. Thanks!
