### ISSUE TITLE
Moving an event

### ISSUE THREAD

**Issue by isene** [itchyny/calendar.vim#119]
How to most effectively move an event from one date/time to another date/time?

**Comment by itchyny** [comment]
For example, press in the event view; `i10:00-10:30<Enter>`.

**Comment by isene** [comment]
That works for changing the time within the original date - but if I add a new date in front, the event isn't moved but simply stays with the date and the time added to the event text. I did this:

i2017-04-27 17:00 - 18:00<Enter>

**Comment by itchyny** [comment]
Okay. `i4-27 17:00 - 4-27 18:00` seems to work but I think I'd better support omitting the latter date.

**Comment by isene** [comment]
Maybe you could add the option to move an event to a new time without specifying the end time and simply use the original event length, i.e. like this:

`i2017-05-01 17:00<ENTER>`

If the original event was 30 minutes, the above would then be equivalent to:

`i2017-05-01 17:00 - 17:30<ENTER>`

**Comment by piotryordanov** [comment]
How exactly do I do that? Where do I add these info?
