### ISSUE TITLE
Problem with display calendar on MacOS

### ISSUE THREAD

**Issue by echuraev** [itchyny/calendar.vim#120]
If I run calendar on mac os then I see the following additional lines on the left side.
<img width="1440" alt="screen shot 2017-05-09 at 09 46 44" src="https://cloud.githubusercontent.com/assets/5525113/25838616/b71ee1a2-349c-11e7-8b48-aade2dd9dd78.png">

**Comment by itchyny** [comment]
Are you using indentLine plugin?

**Comment by echuraev** [comment]
Yes, but I use indentLine on my work pc (Ubuntu 14.04 and RedHat 7.0) and I don't have the same lines. Is it possible to disable this plugin only for calendar.vim?

Also, today I updated version of calendar.vim on my mac machine and calendar isn't working now. I got the following error: 
```
Error detected while processing function 137[16]..129[2]..134[4]..181[27]..212[1]..253[1]..414[8]..413[21]..279[8]..277[1]..287[16]..calendar#google#calendar#getEvents:
line   27:
E706: Variable type mismatch for: c
Error detected while processing function 137[16]..129[2]..134[4]..181:
line   27:
E706: Variable type mismatch for: r
Press ENTER or type command to continue
```

Do you know what is it?

Thank you in advance.

**Comment by itchyny** [comment]
Oops, the E706 error was due to my small error, sorry.

**Comment by itchyny** [comment]
I think you can use `g:indentLine_fileTypeExclude` to disable the plugin in calendar buffer.

**Comment by echuraev** [comment]
Thank you. Now it works. Unfortunately `g:indentLine_fileTypeExclude` isn't working for this case. But I'll try to find solution.
