### ISSUE TITLE
Undefined variable: g:colors_name

### ISSUE THREAD

**Issue by martonbalazs** [itchyny/calendar.vim#121]
Hi, since upgrading to a recent commit I get plenty of errors at startup, and during navigation. I have Xubuntu 16.04, tried in gnome-terminal, xfce4-terminal and xterm, error was always present. Even gvim has problems. Removed my .vimrc, no change.

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056

Any more info I could provide? Many thanks in advance. Here is my startup screen after :Calendar:

Error detected while processing function calendar#color#normal_fg_color[8]..calendar#color#fg_color[2]..calendar#color#to_256color[7]..calendar#color#is_dark:

line    4:
E121: Undefined variable: g:colors_name
E15: Invalid expression: g:colors_name
Error detected while processing function calendar#color#normal_bg_color[8]..calendar#color#bg_color[2]..calendar#color#to_256color[9]..calendar#color#is_dark:

line    4:
E121: Undefined variable: g:colors_name
E15: Invalid expression: g:colors_name
Error detected while processing function calendar#color#comment_fg_color[4]..calendar#color#fg_color[2]..calendar#color#to_256color[7]..calendar#color#is_dark
:
line    4:
E121: Undefined variable: g:colors_name
E15: Invalid expression: g:colors_name
Error detected while processing function calendar#color#is_dark:
line    4:
E121: Undefined variable: g:colors_name
E15: Invalid expression: g:colors_name
Error detected while processing function calendar#color#syntax:
line    9:
E421: Colour name or number not recognised: ctermfg=-1 ctermbg=-1
E421: Colour name or number not recognised: ctermfg=-1 ctermbg=236
Error detected while processing function calendar#new[19]..28[3]..30[2]..35[4]..82[27]..113[1]..154[1]..324[1]..323[26]..193[8]..191[1]..201[16]..calendar#goo
gle#calendar#getEvents[1]..calendar#color#is_dark:
line    4:
E121: Undefined variable: g:colors_name
E15: Invalid expression: g:colors_name

**Comment by itchyny** [comment]
Sorry, I fixed the error.

**Comment by martonbalazs** [comment]
This is great, works perfectly again, thank you so much!
