### ISSUE TITLE
Can we write diary in the calendar?

### ISSUE THREAD

**Issue by jueqingsizhe66** [itchyny/calendar.vim#122]
If we can click Enter key to write a diary, that will be more perfect, just like
[calendar-vim](https://github.com/mattn/calendar-vim)  links with [vimwiki/vimwiki](https://github.com/vimwiki/vimwiki)

Some notes from calendar-vim:
```
                                                *g:calendar_diary*
Specify the directory for the diary files.  The default value is $HOME/diary.
  let g:calendar_diary=$HOME.'/.vim/diary'
```

**Comment by itchyny** [comment]
There's no vimwiki integration for this app and there's no plan to, sorry. But I do write my own diary as day event in Google Calendar via calendar.vim (of course).

**Comment by jueqingsizhe66** [comment]
okay,3x, also good app!
