### ISSUE TITLE
Display months' name instead of number

### ISSUE THREAD

**Issue by piotryordanov** [itchyny/calendar.vim#123]
Is it possible to display the month's name instead of the number?

For example: `June` instead of `6` ?

Thank you for the freaking sexy awesome plugin :)

**Comment by itchyny** [comment]
You might want `let g:calendar_date_full_month_name = 1`.

**Comment by piotryordanov** [comment]
That works. Thank you!

Btw, is there a way of completeing an event but not deleting it, just like with tasks?

**Comment by itchyny** [comment]
Sorry, I'm afraid there's no _complete an event_ feature in Google Calendar... or are you using this app without connecting to Google Calendar?

**Comment by piotryordanov** [comment]
No, I'm not using GCal. Just local calendar. (Where is it stored btw? Can it be backed up?)

**Comment by itchyny** [comment]
OK. But I'm not going to implement the feature, sorry. Events are stored in `~/.vim/cache/calendar/`.

**Comment by piotryordanov** [comment]
No worries. I guess if an event can be marked as 'done', I could create a command that would move the event out of the main calendar.
It's not a must feature anwy. Thanks for the swift support!

**Comment by itchyny** [comment]
Thank you.

**Comment by piotryordanov** [comment]
Is there a way to change the location of the calendars?

**Comment by itchyny** [comment]
Yes, consult `:h calendar.vim` and search for `cache_directory`.

**Comment by piotryordanov** [comment]
Thx that did it!
