### ISSUE TITLE
Add option to set default calendar index when inserting new event

### ISSUE THREAD

**Issue by courtyardz** [itchyny/calendar.vim#125]
When hitting `i` to insert, I get an annoying prompt:

~~~~
index title
[ 0]  connoreck87@gmail.com
  1   Contacts
Input the index of the calendar:
~~~~

I never want to insert new events into `Contacts`. How do you recommend avoiding this prompt?

**Comment by eLefTrick6** [comment]
I receive this prompt also when playing around I had created a second calendar (not synced with GCal yet). How can the calendars be modified or unused be removed after they are created?

**Comment by itchyny** [comment]
This is resolved by g:calendar_calendar_candidates (refer to [`:h g:calendar_calendar_candidates`](https://github.com/itchyny/calendar.vim/blob/84335b66be1e323002380280f265983dc635fd99/doc/calendar.txt#L421-L427)).
