### ISSUE TITLE
Sorting of events in a given day

### ISSUE THREAD

**Issue by isene** [itchyny/calendar.vim#132]
As it is now, events are sorted by the first number regardless of the time format. It should be sorted by time. Example:

Current sorting:
11:30 Meeting
14:00 Call John
9:30 Call Anna

Should be:
9:30 Call Anna
11:30 Meeting
14:00 Call John

(alternatively, all single digit hours could be prefixed with "0", i.e. 9:30 => 09:30. This would make the sorting work as intended).

**Comment by itchyny** [comment]
I cannot reproduce but there might be some situation that sort fails. I don't know why...

<img width="224" alt="screen shot 2017-12-13 at 8 45 54" src="https://user-images.githubusercontent.com/375258/33914542-0d77dca2-dfe2-11e7-82f0-91b4dbd2c778.png">

**Comment by isene** [comment]
Here's mine: http://isene.org/x/2017-12-13-093308_622x466_scrot.png

**Comment by isene** [comment]
Could we in any case change 9:30 => 09:30 ?

**Comment by itchyny** [comment]
I have fixed the problem, sort considering events without duration. Let me keep the format of the hour because it will be a big change across the plugin code.

**Comment by isene** [comment]
OK. Thanks for the update. Works fine now :-)
