### ISSUE TITLE
Color not working if set termguicolors.

### ISSUE THREAD

**Issue by kiooss** [itchyny/calendar.vim#135]
minimal vimrc:

```
call plug#begin()
Plug 'itchyny/calendar.vim'
call plug#end()
set termguicolors
set background=dark
syntax on
```

Screenshot:
<img width="1924" alt="screencapture 2018-03-12 17 21 12" src="https://user-images.githubusercontent.com/842321/37275447-374a0b6c-261a-11e8-9f2b-dfcdcadfd6e6.png">

Screenshot (Without termguicolors):
<img width="1924" alt="screencapture 2018-03-12 17 22 17" src="https://user-images.githubusercontent.com/842321/37275480-5072bbac-261a-11e8-97f8-a24c8fb12cca.png">

**Comment by itchyny** [comment]
Thanks for your report, I have fixed the problem.

**Comment by kiooss** [comment]
Thanks for the quick response. It works like a charm :)
