### ISSUE TITLE
Feature request: Wrap to next date on month view

### ISSUE THREAD

**Issue by isene** [itchyny/calendar.vim#139]
Could we have a wrap to next weeks first date and last day in previous week when in month view?

**Comment by itchyny** [comment]
Press `w` or `b` to wrap around.

**Comment by isene** [comment]
Would it be possible to easily map w and b to the right and left keys so it would simply keep wrapping both ways?


On Mon, Jul 16, 2018 at 22:16:11(pm) -0700, itchyny scribed:
> Press `w` or `b` to wrap around.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/itchyny/calendar.vim/issues/139#issuecomment-405462084

-- 
	       "This above all: to thine own self be true,
		And it must follow, as the night the day,
		 Thou canst not then be false to any man"
				    (William Shakespeare)

Geir Isene: http://isene.com | http://no.linkedin.com/in/isene | +47-4550 2470
Company: A-Circle AS (Å) - You. Your company. Boosted | http://www.a-circle.no

**Comment by itchyny** [comment]
```vim
autocmd FileType calendar nmap <buffer> <left> <Plug>(calendar_prev)
autocmd FileType calendar nmap <buffer> <right> <Plug>(calendar_next)
```

**Comment by isene** [comment]
Thanks :-)

On Tue, Jul 17, 2018 at 14:37:15(pm) +0000, itchyny scribed:
> ```vim
> autocmd FileType calendar nmap <buffer> <left> <Plug>(calendar_prev)
> autocmd FileType calendar nmap <buffer> <right> <Plug>(calendar_next)
> ```
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/itchyny/calendar.vim/issues/139#issuecomment-405605141

-- 
		    "Pappa, tror du på virkeligheten?"
				   (Jonatan, 5 år)

Geir Isene: http://isene.com | http://no.linkedin.com/in/isene | +47-4550 2470
Company: A-Circle AS (Å) - You. Your company. Boosted | http://www.a-circle.no
