### ISSUE TITLE
Error detected by starting calendar

### ISSUE THREAD

**Issue by andalou** [itchyny/calendar.vim#143]
I've installed Calendar on vim 8.1.500 under Windows 7.
When I do :Calendar I get:

--------------------
Error detected while processing function calendar#color#syntax:
line 9:
E411: highlight group not found: CalendarNormalSpace
--------------------

Many thanks in advance,

Cesar

**Comment by itchyny** [comment]
Can you test the command `:echo [calendar#color#normal_fg_color(), calendar#color#normal_bg_color()]` ?

**Comment by andalou** [comment]
I get:

    ['', '']

**Comment by itchyny** [comment]
Can you test `:hi Normal` and `:echo has('gui_running') || (has('termguicolors') && &termguicolors)` ?

**Comment by andalou** [comment]
:hi Normal

gives

    Normal xxx font=Lucida_Console:h10:cANSI:qDRAFT

    :echo has('gui_running') || (has('termguicolors') && &termguicolors)

gives

    1

**Comment by itchyny** [comment]
I fixed the bug, thanks for your report.
