### ISSUE TITLE
vim +Calendar color scheme

### ISSUE THREAD

**Issue by rogershijin** [itchyny/calendar.vim#145]
I would like to start calendar.vim from the command line, and it seems like the way to do it is

`vim +Calendar`

but when I run this command the color scheme is a bit off:
![image](https://user-images.githubusercontent.com/27650355/52204563-85d82b80-2842-11e9-814c-4376b85b4457.png)

This doesn't really change the functionality but is there a way to set the color scheme back to the original? 

![image](https://user-images.githubusercontent.com/27650355/52204598-9e484600-2842-11e9-86f1-fc5db38cf3e5.png)

Thanks!

I am running this on Arch Linux.

**Comment by itchyny** [comment]
This is weird and unreproducible. Can you give me minimal vimrc to reproduce the issue or link to your vimrc. Also, please let me know the output of `:colorscheme`, `:set bg` and `:echo calendar#color#is_dark()`.

**Comment by rogershijin** [comment]
:colorscheme - default 
:set bg - background=dark  
:echo calendar#color#is_dark() - 1 

The issue happens when my .vimrc is just the following:
![image](https://user-images.githubusercontent.com/27650355/53606557-34913280-3b89-11e9-9589-3e7612a58665.png)

And my .bashrc is empty.  Does this imply it's a system-specific issue?
