### ISSUE TITLE
move event to another day/time?

### ISSUE THREAD

**Issue by divramod** [itchyny/calendar.vim#147]
hey, this is a really awesome plugin!!!!

i searched, but couldn't find how to move a event to another day or time.
Is this somehow built in?

thx for the awesome work.
seems to be my missing link for going mouseless :-)

**Comment by rwev** [comment]
I was wondering about this too. I have found that the easiest way is just to delete the entry you want to move and re-adding the event. Keep in mind, you don't need to to enter the full date / time ranges and event title; you can access the previous cached entries with <UP> from the EVENT: buffer.
