### ISSUE TITLE
Could really use routines. And some tweaks to recursian

### ISSUE THREAD

**Issue by flareriderdash** [itchyny/calendar.vim#149]
The ability to create routines that hold other smaller events in them
would be a great addition to Calcurse. I have an alternating schedule
that follows a pattern of one and the other (e.g. A B A B C NULL NULL)
and even though this is possible to create such patterns without
routines it is very labor intensive to actually achieve this. I could
just copy and paste every event to the days needed during the week and
then set recursion for every week on every single one of the events.
This would be feasible, but again, very slow and even inflexible to new
start times as each event is time specific where a routine could be
independent from this. The routine would serve like an event holding
other events and those events inside this routine would be relative to
the start time of the routine (whatever the user may choose that to be)
allowing flexibility and plug and playness to reoccurring sets of
events.  This would make a set of events' recursion nicer, as not all of
the contained events need recursion flags (saving time and making
everything neat).

Now referring back to my interesting recursion of my schedule as the
pattern shown above (A B A B C NULL NULL) It would be easier to think
about and also make sense to add an additional option to the weekly
recursive setting to not only ask the interval of weeks between events
(or routines) but also on what days of the week the user wants it.

e.g.  User wants his bi-weekly cake party to be on Mondays and
Thursdays.

The above example is not possible with the current way of recursion as
how it is calculated now is based off an offset from the current week
that only corresponding to the day that the event was created on(i.e.
The event created on Tuesday can only be made to be recursive on
Tuesdays of every week). Instead you would have to create a copy of the
event(or routine) on other desired days; and this seems just unnecessary
to do since If you have many events it can become unnecessarily taxing
on the user to create it. Other similar ideas can be applied to the
other recursion options, but as it pertains to me (I've only used weekly
and daily recursion ) weekly should have this.

**Comment by flareriderdash** [comment]
Also do note that my schedule (A B A B C NULL NULL) represents my routines for each day. Starting on a monday and ending on a sunday.

**Comment by itchyny** [comment]
If I'm correct, you're requesting something like the following recursion configuration (please request features more briefly). This looks like a part of  #129. But currently there's no plan to support such complex recursion feature (because I don't need something like this).
<img width="394" alt="Screenshot 2022-12-25 at 11 28 41" src="https://user-images.githubusercontent.com/375258/209455293-e6f84a5a-1d9d-41f7-8e65-942f19b83f21.png">
