### ISSUE TITLE
how to connect to google calendar

### ISSUE THREAD

**Issue by laoyang945** [itchyny/calendar.vim#150]
hi i set g:calendar_google_calendar = 1 in .vimrc
and open calendar.vim, a webpage is opened in chrome ask for permission and after i authorise, google said:
Please copy this code, switch to your application and paste it there:

where am i supposed to paste the auth code?
thanks very much

**Comment by itchyny** [comment]
The plugin wants to authorize so please paste the code to the Vim prompt. The plugin should wait for the auth code as follows.
<img width="421" alt="Screen Shot 2019-06-19 at 22 50 11" src="https://user-images.githubusercontent.com/375258/59771433-a6ca8600-92e4-11e9-9a23-e09a117d5a45.png">

**Comment by laoyang945** [comment]
i see. i have some auto saving mechanism when vim is out of focus. after i switch off the function, i can connect to google calendar.
thanks for the great work!
