### ISSUE TITLE
Long delay for prompt to delete event

### ISSUE THREAD

**Issue by rwev** [itchyny/calendar.vim#152]
When I am viewing the "Event List" for a given day, and press "`dd`" on one of the events to delete it, the confirmation prompt ("`Delete the event? (cannot be undone) y/N`") doesn't appear for a full second or more. 

This is strange because I haven't noticed such delay anywhere else in the program; other operations seem to be snappy and responsive. Is anyone else experiencing this?

I'm running vim 8.0 through the Windows subsystem.

**Comment by itchyny** [comment]
This behavior might be caused by yanking the event text. Try `let g:calendar_yank_deleting = 0` to see if it improves.

**Comment by rwev** [comment]
I just tried this and did not notice a difference.

**Comment by itchyny** [comment]
I cannot reproduce this. Please take a profile. Try `:profile start profile.log | profile func *` and open calendar.
