### ISSUE TITLE
Sign in with Google temporarily disabled for this app error

### ISSUE THREAD

**Issue by pahakalle** [itchyny/calendar.vim#156]
When i open the calendar and it gives me the link to sign in with google i get this error after selecting my account
<img width="673" alt="Screenshot 55" src="https://user-images.githubusercontent.com/1533244/70398211-c46de200-1a21-11ea-95e2-196ce06702af.png">

**Comment by itchyny** [comment]
Okay, I failed to take action to the mail from Google API Team. I submitted verification so waiting for the response.

**Comment by chrisersen** [comment]
I'm getting the same message as pahakalle :(

**Comment by itchyny** [comment]
Sorry about this, I submitted an OAuth App Verification request on Dec 2019 but failed due to this application does not have website. I mailed to the GCP/API Trust & Safety team however they didn't send me for weeks about the verification way for this kind of application. I'm considering taking some domain and try to resubmit the verification.

**Comment by chrisersen** [comment]
Thanks for your fast response and your efforts! (And of course the nice vim-app!)

**Comment by pahakalle** [comment]
@itchyny Setup a quick wiki page with github pages. That might be enough

**Comment by itchyny** [comment]
They require the ownership of the authorized domain via Search Console (see https://support.google.com/cloud/answer/9110914), but I think there're many application which is distributed only from GitHub. I believe they should provide a solution for this.

**Comment by ksonney** [comment]
Is there a simple way to put in my own Google keys and set it up as a "development" app under my own account? That would provide a stopgap until this is sorted.

**Comment by glazari** [comment]
Hello, 
I'm also interested in the solution (or workaround) for this problem :)

**Comment by itchyny** [comment]
Here's a workaround https://github.com/itchyny/calendar.vim#important-notice.

**Comment by liston** [comment]
Can anyone confirm that the workaround is working for them, as it does not for me, still getting the disabled this app message.

**Comment by itchyny** [comment]
@liston Did you update the calendar plugin?

**Comment by ksonney** [comment]
@liston It works for me after updating to the latest version of the plugin.

**Comment by liston** [comment]
Thanks guys, I was getting a lot of commit errors, so I deleted the plugin and re-installed and it works now.

**Comment by SkyLeach** [comment]
is this issue related?

https://github.com/itchyny/calendar.vim/issues/171#issuecomment-689549278
