### ISSUE TITLE
Set color for events

### ISSUE THREAD

**Issue by hzchirs** [itchyny/calendar.vim#158]
I noticed that events highlighted by the color set in google calendar. 
But I don't find how to set color in help document.
Is there any way to set color for events? Thanks

**Comment by itchyny** [comment]
You mean you want to use different colors than they look in google calendar, right?

**Comment by hzchirs** [comment]
Yes, for example: 
<img width="1413" alt="截圖 2019-12-23 上午11 26 46" src="https://user-images.githubusercontent.com/4735528/71334065-71df0a80-2577-11ea-9ce0-caae1086c8b8.png">

**Comment by itchyny** [comment]
I don't think I implement this so closing, sorry.

**Comment by hzchirs** [comment]
Sorry I'm not good at in English. can't get your meaning. 
Did you mean you will not implement this feature?
