### ISSUE TITLE
Can I create an event from full-text input?

### ISSUE THREAD

**Issue by llinfeng** [itchyny/calendar.vim#160]
On the web-interface, Google Calendar no longer take full-text inputs with **dates**. 

I wonder if `calendar.vim` offers a feature to take full-text input and create an event on the **date** and **time** as specified in the full-text input? It would wonderful if recurrent events can also be converted from plain text :)

For example, full-text entries include:
* Breakfast at 8 am, Sunday
* Car Maintenance at 7 am, Mar 10.
* Dad's Birthday, April 27, every year

**Comment by itchyny** [comment]
Please refer to `:h calendar-input-format`.
