### ISSUE TITLE
How can I fix this messy encoding?

### ISSUE THREAD

**Issue by yaohunzhanyue** [itchyny/calendar.vim#163]
![image](https://user-images.githubusercontent.com/18609294/77500263-817c3100-6e8f-11ea-9dc1-2b1b6bc6e872.png)
This plugin works fine till I reinstall it, then it became like this.

**Comment by itchyny** [comment]
What `:echo [v:lang, &enc]` outputs?

**Comment by yaohunzhanyue** [comment]
@itchyny ['zh_CN', 'utf-8']

**Comment by itchyny** [comment]
Please try the following command to see the output.
`:echo map(range(3, 9), "strftime('%a', 60 * 60 * (24 * v:val + 10))")`

**Comment by yaohunzhanyue** [comment]
@itchyny ['????', '??涓??', '??浜??', '??涓??', '????', '??浜??', '????']

**Comment by itchyny** [comment]
Add both `:language message en_US.UTF-8` and `:language time en_US.UTF-8` to your vimrc and please restart Vim.

**Comment by yaohunzhanyue** [comment]
@itchyny Great, it works, tks~
