### ISSUE TITLE
After daylight saving, all events are off by one hour

### ISSUE THREAD

**Issue by isene** [itchyny/calendar.vim#165]
Last month, Norway entered Daylight saving time. In Google calendar on the web, the events are displayed correctly, but in calendar.vim, they are displayed one hour earlier. How to fix?

**Comment by itchyny** [comment]
First of all, the plugin does not support DST switch (#142) and there's no plan to support it for now. The timezone of the plugin follows the timezone of the environment (like `date` command). So one option is to configure the environment (maybe `TZ`). And another option is to configure `g:calendar_time_zone` (See `:h g:calendar_time_zone).

**Comment by isene** [comment]
I found the issue here - it's that I didn't restart VIM after DST. Doing that updated the appointment times and all is fine. Maybe add a note in the docs on that?

**Comment by itchyny** [comment]
Hmm, restarting something is in general the solution for various kind of problems (not only for this DST problem), so I don't think documentation is appropriate.
