### ISSUE TITLE
Feature Request: Google Calendar Lazy Syncing

### ISSUE THREAD

**Issue by rogershijin** [itchyny/calendar.vim#166]
I found that after syncing with Google Calendar, there's a delay when modifying the calendar _locally._  Newly added local events can take up to ~30 seconds to show up on the calendar.vim UI.  Would it be possible to have these show up immediately (possibly with a syncing icon) and perform the sync with Google Calendar in the background?

**Comment by itchyny** [comment]
This feature will make the state management much more complex and I cannot maintain. In my environment the new event shows in a few seconds and I'm satisfied with it. Sorry but closing.
