### ISSUE TITLE
Hotkey for left view doesn't work

### ISSUE THREAD

**Issue by fuelen** [itchyny/calendar.vim#167]
I can use "zoom" view but unable to go back.
[My config if needed](https://github.com/fuelen/nvimfiles/blob/master/init.vim)
```
$ LC_ALL=C nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by itchyny** [comment]
What does `:map <` output?

**Comment by fuelen** [comment]
![Знімок екрану Deepin_вибрати-область_20200427104215](https://user-images.githubusercontent.com/588762/80346763-ee5e5e80-8873-11ea-9495-3e6ec8c33a23.png)

**Comment by fuelen** [comment]
Weird. It works from terminal, but doesn't work in `nvim-qt`

**Comment by itchyny** [comment]
I builded neovim-qt and tried minimal setup (only calendar.vim installed) but can't reproduce this issue.

**Comment by fuelen** [comment]
neovim-qt version from official arch linux repositories contains this bug, but latest version from master works well :tada: 
Thank you for help!
