### ISSUE TITLE
How to format/edit tasks?

### ISSUE THREAD

**Issue by gennaro-tedesco** [itchyny/calendar.vim#168]
Where can I find documentation on the correct formatting for the task list? I cannot seem to find instructions beyond inserting/deleting tasks.

What I would like to do is the following:
- insert bullet points
- insert new lines
- use vim keys/shortcuts in the task view

are the above possible at all?

**Comment by itchyny** [comment]
In order to edit a task, use i or a. I don't get what you mean by bullet points, but to mark completed tasks, use D (and undo with U).

**Comment by gennaro-tedesco** [comment]
I would like to itemise the entries in the task list like the following:
```
- first task
- second task
- ...
```
but carriage return exits the task mode; however, I have realised that `o` does produce a new line that I can use for indentation. 

Furthermore: is visual mode not allowed in task/even mode?

**Comment by itchyny** [comment]
What do you want visual mode for?

**Comment by gennaro-tedesco** [comment]
> What do you want visual mode for?

Mainly to be able to select blocks of text at once and manipulate them more easily. However, I was only wondering if I had missed the documentation somewhere: I am not arguing that such modes must be present, the plug-in is fine as it is :).

**Comment by itchyny** [comment]
I admit that the current editing way is not flexible but currently such modes are not implemented.
