### ISSUE TITLE
Buggy experience with tasks

### ISSUE THREAD

**Issue by wallace11** [itchyny/calendar.vim#174]
There are a couple of problems I'm experiencing with tasks.
They might be all connected so I thought I'd write them all together, but if you want I can open separate issues.

1. Task lists are not properly synchronized. I have 3 lists: "My to-dos" (the default), "test" and "new". "test" shows as "My Tasks" and "new" isn't showing at all.
2. Completing a task (pressing `D`) simply wipes its description, but it stays as an empty item on the list. On google tasks it shows as "completed" buy description is missing (all completed tasks are empty).

Please keep up your great work :)

**Comment by itchyny** [comment]
The second issue is fixed for now.

**Comment by wallace11** [comment]
Thanks for your fast response.

1. Tasklist names syncs perfectly now
2. I'm able to complete a task (`D`) and clear (`L`)

All issues resolved, as far as I can tell!
It sounded as though you still had some work you wanted to do, so I'll leave closing this issue to you.
Thank you :)

**Comment by itchyny** [comment]
Thanks.
