### ISSUE TITLE
Feature request: fetch data

### ISSUE THREAD

**Issue by wallace11** [itchyny/calendar.vim#177]
Having to relaunch `:Calendar` each time there's an update to the calendar (new invitation, for example), is quite a pain, so I thought maybe there's an easy way to solve this problem. 

Simply add a mapping to manually fetch data from Google which will effectively refresh the calendar + tasks just as it does when launching. Maybe <kbd>R</kbd> (<kbd>shift+r</kbd>) is a good idea for a default keybinding. 

Also, it may be be a good idea to implement a threshold for manual refreshing, that'd prevent multiple API calls (10s maybe?).

This is a different and probably more sane approach to #166.

**Comment by itchyny** [comment]
You can use `<C-r>`.

**Comment by wallace11** [comment]
Alright, now we're talking!
The Only problem is that it won't refetch tasks.
Would you like me to open a separate issue for that?

Also, maybe phrasing in the help file could be improved since I completely
misunderstood the function of that xD

**Comment by itchyny** [comment]
> The Only problem is that it won't refetch tasks.

This has been fixed.

**Comment by rogershijin** [comment]
@wallace11 about your reference to #166 , sorry for being unclear, I was more talking about event upload to Google Calendar adding a lag of a second or two when creating new events on the Calendar.vim GUI, as opposed to event download from Google Calendar.  Though I suppose the `<C-r>` idea would be helpful if there were a way to turn off automatic upload to Google Calendar and then sync on demand with `<C-r>`.  Maybe that's what you were talking about?
