### ISSUE TITLE
Error after cloning calendar.vim into ~/.vim/plugin

### ISSUE THREAD

**Issue by Pedro-vzla** [itchyny/calendar.vim#178]
hi, first of all thank you so much for making this wonderful plugin for vim, I didn't think two times to try it, but unfortunately I cant fix the problems by mi own, so I tried to isntall with the vim plugin manager:
* I first cd int ~/.vim/plugin
* git clone https://github.com/itchyny/calendar.vim
* then when i start vim this output of "start.log" file comes, then vim starts normally
* then when vim starts i type :Calendar<CR>, and i get the output of "cal.log" file
[start.log](https://github.com/itchyny/calendar.vim/files/5011551/start.log)
[cal.log](https://github.com/itchyny/calendar.vim/files/5011513/cal.log)

I tried to put all inside calendar.vim folder inside a new "start" folder bot the same result.
By the way, i'm in Arch linux and this is my vim compilation:
[compilation.txt](https://github.com/itchyny/calendar.vim/files/5011554/compilation.txt)

**Comment by itchyny** [comment]
You can't clone this plugin to ~/.vim/plugin. Please use a plugin manager like [vim-plug](https://github.com/junegunn/vim-plug).

**Comment by Pedro-vzla** [comment]
OMG!! sry, so I will try with my plugin manager, by the way is vundle, calendar.vim works whit vundle to??

**Comment by itchyny** [comment]
Yes, it should work with vundle too.
