### ISSUE TITLE
Wrapping Days in Sequence in Visual Mode

### ISSUE THREAD

**Issue by coleastaire** [itchyny/calendar.vim#179]
It would be great if while in visual mode, continuously selecting to the right or left would select days in sequence. For example, currently, attempting to move to the right from a Saturday simply stops the selection, rather than wrapping to the next day in the sequence, Sunday. Similarly this doesn't happens when attempting to move left from a Sunday back to Saturday.

**Comment by itchyny** [comment]
You are using `l` and `h` right? These mappings stops at the ends and `w` and `b` wrap. They are expected to behave as same as in the normal buffers.

**Comment by coleastaire** [comment]
I was not using l and h. Thanks!
