### ISSUE TITLE
Support for am/pm

### ISSUE THREAD

**Issue by rogershijin** [itchyny/calendar.vim#183]
Since I'm in the US, I find it a bit hard to wrap my head around the 24-hour clock.  Would you be willing to support inputs like

`:EVENT 1:00pm-1:30pm eventname`?

**Comment by miko007** [comment]
you literally have to add 12 hours if it is pm. should not be that hard...

**Comment by itchyny** [comment]
I implemented this feature. Any of `1:00 pm`, `1:00 PM`, `1:00 p.m.`, `1:00 P.M.` and without spaces are supported.

**Comment by rogershijin** [comment]
Thank you so much!
