### ISSUE TITLE
Use color events with local calendar

### ISSUE THREAD

**Issue by dtrckd** [itchyny/calendar.vim#184]
Hi,

Is is possible to use colored event when storing event in local mode ?

If not, do you have a hint of where in a code I can look to try to implement that feature ?

**Comment by itchyny** [comment]
I believe [the colors are assigned automatically on creating a new calendar](https://github.com/itchyny/calendar.vim/blob/e276e5033623535264786398f46d0ff05c37297e/autoload/calendar/event/local.vim#L219-L228), but if you wish you can edit `~/.cache/calendar.vim/local/calendarList` directly.

**Comment by dtrckd** [comment]
I was not obvious that we can just add a new entry with new ID and color in this file, but that works !

Thanks you @itchyny.
