### ISSUE TITLE
Event pop-up has title 3 PM

### ISSUE THREAD

**Issue by SureshGovindachar** [itchyny/calendar.vim#187]
On typing 'E', the pop-up has the title "3 PM" and there does not seem to be any way to change this title:

             
        +------------------------------------+
        |                3 PM                |
        |                                    |
        | 14:00 - 13:15 Second entry, 1 PM   |
        | 15:00 - 15:15 First entry, 3 PM    |
        |                                    |

**Comment by itchyny** [comment]
Edit the JSON file `local/calendarList` in the cache directory. There's no plan to implement feature for editing calendar title.
