### ISSUE TITLE
Using pass as an alternative to store google credentials

### ISSUE THREAD

**Issue by ChausseBenjamin** [itchyny/calendar.vim#192]
[pass](https://www.passwordstore.org/) is a great tool to store encrypted passwords.
I think it would be more usefull to have this tool store a users google credentials as it is easier to setup (and more secure).
An example setup could be:
```(bash)
$ pass insert calendar-vim/google-api-key
mkdir: created directory '/home/user/.password-store/calendar-vim'
Enter password for calendar-vim/google-api-key: _
```
So all the credentials could be stored as:
- `calendar-vim/google-api-key`
- `calendar-vim/google-client-id`
-  `calendar-vim/google-client-secret`

**Comment by itchyny** [comment]
It's unlikely to implement features depending on tools like this, sorry.
