### ISSUE TITLE
Identification ?

### ISSUE THREAD

**Issue by YabDzil** [itchyny/calendar.vim#194]
Hello,

trying to follow your link:
--->https://opensource.com/article/20/1/vim-email-calendar

====> *+lundi-15-février-2021+++10:27:25*  [ ~/.vim/bundle ] 2036 
\---> [0] -->>> git clone git@github.com:itchyny/calendar.vim.git
Clonage dans 'calendar.vim'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
***************************************************************************************
Thank's in advance.

**Comment by itchyny** [comment]
Try `git clone https://github.com/itchyny/calendar.vim.git`

**Comment by YabDzil** [comment]
-->>> git clone https://github.com/itchyny/calendar.vim.git
Clonage dans 'calendar.vim'...
remote: Enumerating objects: 228, done.
remote: Counting objects: 100% (228/228), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 2745 (delta 120), reused 179 (delta 83), pack-reused 2517
Réception d'objets: 100% (2745/2745), 555.95 KiB | 331.00 KiB/s, fait.
Résolution des deltas: 100% (1582/1582), fait.
Vérification de la connectivité... fait.

************************Hip ! Hip ! :100:
