### ISSUE TITLE
Move tasks up/down aka changing priority

### ISSUE THREAD

**Issue by mmskv** [itchyny/calendar.vim#195]
Thank you for making this awesome application!

I can't figure out how to move tasks up or down in the task list, though if i move task in google calendar, it moves in the application's list after a while.

By the way, is there a way to avoid closing task list when pressing `<Esc>`? I have a habit of pressing `<Esc>` before navigating in vim to ensure that I'm in a normal mode

**Comment by itchyny** [comment]
<kbd>C-k</kbd> is mapped to <kbd>&lt;Plug&gt;(calendar_move_up)</kbd> and <kbd>C-j</kbd> is mapped to <kbd>&lt;Plug&gt;(calendar_move_down)</kbd>

**Comment by mmskv** [comment]
Thank you very much!
