### ISSUE TITLE
Year view doesn't highlight current day on weekends

### ISSUE THREAD

**Issue by sathishbaskar** [itchyny/calendar.vim#196]
For e.g. below command doesn't give current day (green) highlight for weekends.

```
:Calendar -view=year -split=horizontal -position=bottom -height=12
```

**Comment by itchyny** [comment]
Aha, regression of 9eb05f05f11ce281bff8b2ee980e70244e29d7ae. Syntax ordering matters. Thanks for reporting.

**Comment by itchyny** [comment]
Fixed.
