### ISSUE TITLE
How to edit the name of an event and how to delete an event?

### ISSUE THREAD

**Issue by llinfeng** [itchyny/calendar.vim#198]
For now, I can only create new events with `i` or `o`. I cannot edit the name of an existing event. Nor can I delete an event created with `i` (or `o`). Please advise how to modify events with calendar.vim.

For my GCP app, I set the scope as the following, which covers both "edit" and "delete". Through this app, the connection did go through after following the steps mentioned in the [important notice](https://github.com/itchyny/calendar.vim#important-notice).
![image](https://user-images.githubusercontent.com/5890407/135487377-37caf739-1176-4f28-a59b-f4d369e17393.png)

I have also tried to assign mappings in the `:Calendar` buffer. Still, none of the keys triggered anything in the Calendar view.
```
nnoremap c <Plug>(calendar_change) 
nnoremap C <Plug>(calendar_change_line) 
nnoremap d <Plug>(calendar_delete)  
nnoremap d <Plug>(calendar_delete_line)
```

I wish I am missing something really simple. In the task panel, both `c` and `d` are working as intended.

**Comment by itchyny** [comment]
By default you can edit and delete events in the event view, which you can show with <kbd>E</kbd>. In the popup, you can edit with <kbd>i</kbd> and <kbd>a</kbd>, and delete with <kbd>dd</kbd> and <kbd>D</kbd>. For customizing the Plug mapping, use `nmap` instead of `nnoremap`.

**Comment by llinfeng** [comment]
Thanks a lot for your clarification! 

Indeed, entering the event view with `E` gets `C` and `D` to work again. (My events have pretty short names. It suffices to either delete them or rename altogether.)

**Comment by ilan-schemoul** [comment]
Is it documented anywhere ? @llinfeng
