### ISSUE TITLE
Auth error for OAuth 2.0

### ISSUE THREAD

**Issue by folofjc** [itchyny/calendar.vim#204]
When attempting to get the code, I get this error from google:

>Authorization Error
>Error 400: invalid_request

>You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

>You can let the app developer know that this app doesn't comply with one or more Google validation rules.

This is in the more info box:
>If you’re the app developer, make sure that these request details comply with Google policies.
>- redirect_uri: urn:ietf:wg:oauth:2.0:oob

That redirect _looks_ like it has 2.0 in it. I don't know anything about OAuth though.

**Comment by itchyny** [comment]
No further description given, and at least it works well for me, so closing. If you have some clue to what's wrong with the plugin, feel free to reopen.

**Comment by itchyny** [comment]
Sorry for closing without investigation. Now I understand the problem, we need to migrate from the OOB flow.

**Comment by itchyny** [comment]
I fixed the OAuth initialization. If you still have interest in this plugin, hope this works in your environment.
