### ISSUE TITLE
Fail in authorization to Google

### ISSUE THREAD

**Issue by LogicNg** [itchyny/calendar.vim#206]
@itchyny thanks for this amazing plugin!

I got "Fail in authorization to Google" after pasted the requested code.  I added

```vim
echom client.client_id
echom client.client_secret
echom client.redirect_uri
echom string(response.content)
```

after line 62, `client_id`, `client_secret` were just the same as the values shown in Google Console. `redirect_uri` = `urn:ietf:wg:oauth:2.0:oob`. However, `response.content` was empty.

https://github.com/itchyny/calendar.vim/blob/fe13024cc3575d83f158339562f0e2d97fb44375/autoload/calendar/google/client.vim#L56-L66

I'm on Win 11.

**Comment by itchyny** [comment]
Hmm, what was the response code?

**Comment by itchyny** [comment]
No further description given, and at least it works well for me, so closing. If you have some clue to what's wrong with the plugin, feel free to reopen.

**Comment by itchyny** [comment]
Sorry for closing without investigation. Now I understand the problem, we need to migrate from the OOB flow.

**Comment by itchyny** [comment]
I fixed the OAuth initialization. If you still have interest in this plugin, hope this works in your environment.
