### ISSUE TITLE
Google authentication doesn't work in Windows 7

### ISSUE THREAD

**Issue by majkinetor** [itchyny/calendar.vim#21]
The problem is in the function

<pre>
function! calendar#webapi#open_url(url)
  if has('win32') || has('win64')
"    silent! call calendar#util#system('start rundll32 url.dll,FileProtocolHandler "' . a:url . '" &')
...
</pre>

I don't know where this method originates but this is simply not the way to launch external url handler in Windows. `url.dll` doesn't exist in my Windows 7. 

I replaced this line with

<pre>     call system( printf('cmd.exe /c start "" "%s"', a:url) ) </pre>

This works and opens default browser where you get the code so you can paste it.

However even if I paste the code I get error that I can not be verified. 

<pre>
curl 7.30.0-DEV (x86_64-pc-win32) libcurl/7.30.0-DEV OpenSSL/1.0.1e zlib/1.2.8 libssh2/1.4.4_DEV
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM SSL libz</pre>

**Comment by robbie-cao** [comment]
I have the same issue to authorize Google in Mac.
My environment https_proxy is also empty. What setting shall I apply to https_proxy?

**Comment by itchyny** [comment]
Do you have `curl` or `wget` installed?

**Comment by robbie-cao** [comment]
Yes, both curl and wget installed
