### ISSUE TITLE
Events not taking all the horizontal space available in week view

### ISSUE THREAD

**Issue by rionda** [itchyny/calendar.vim#213]
In week Some events do not use the whole "cell" even if it is available (i.e., no other event is happening at the same time).

Even when there are two or more events at the same, it seems that the one most on the right could take slightly more space (there is some empty space on the right, which is not present when there is a single event).

See screenshot, specifically on Thursday and Friday afternoons.
![Screen Shot 2023-01-11 at 7 21 27 PM](https://user-images.githubusercontent.com/1178354/211946813-dcf0d31e-6d23-432d-9a33-5788296e634b.png)

**Comment by itchyny** [comment]
Thanks for reporting, I fixed the problem.
