### ISSUE TITLE
Options that set event item's background ? (now skeleton)

### ISSUE THREAD

**Issue by riodelphino** [itchyny/calendar.vim#217]
Thank you for developping this plugin !

In my settings, `:Calendar` appear like below. 
```
test──────┐
└─────────┘ 
test───────
```
Upper event is 60min. Lower is 30min.
All events appear as skeleton with line without background color.
Foreground color is set, same as the color I set in Google Calendar.

Which option switches this appearance to the painted background (without line chars) like [this image](https://raw.githubusercontent.com/wiki/itchyny/calendar.vim/image/image.png) ?

I checked the doc & code, but sorry i can't find it.

**Comment by itchyny** [comment]
Could you share the screenshot?

**Comment by riodelphino** [comment]
Like below.
<img width="312" alt="スクリーンショット 2023-02-23 23 18 44" src="https://user-images.githubusercontent.com/29378271/220933577-4bb80f84-8ebe-4d25-9b45-1018ac7d42a5.png">

Foreground colors are collect. But all are skelton.
It is hard to overlook ^^;

**Comment by itchyny** [comment]
This is an intentional appearance for dark background. When I use calendar colors for dark background, the appearance looks too vivid and ugly.

**Comment by riodelphino** [comment]
I see that this is an intentional appearance.
I think `s:is_dark` variable is the point, so I will try to fork if I can.
Thank you for reply !
