### ISSUE TITLE
Clearing the calendar

### ISSUE THREAD

**Issue by ssossah** [itchyny/calendar.vim#227]
Is there a way to completely clear the calendar such that all tasks and events get removed? I have not made changes to interact directly with google calendar so I just want to be able to make changes locally to start anew. I ran into an issue where the title when typing `E` within the events page was completely modified and I have not been able to reset/change the name. I tried clearing the cache by removing the ~/.cache/calendar.vim directory but it automatically regenerates when I call `:Calendar` with all of the events/tasks I had previously set and the title from the events page remains to be that weird value. Any help would be appreciated!

**Comment by itchyny** [comment]
I don't understand what's happening. Once you delete the `~/.cache/calendar.vim/`, the plugin is initialized completely.

**Comment by smsossah** [comment]
I have switched computers and am no longer running into that issue. It's possible that it was in a weird state, but it's now working again. Thank you for your response!
