### ISSUE TITLE
Delete calendar?

### ISSUE THREAD

**Issue by ACOTSAE** [itchyny/calendar.vim#229]
I didn't connect my Google account, because I just want to keep everything local. I found if I didn't have any calendars, the plugin would notice me to create a new calendar. But I didn't find any way to delete the local calendar I created.

How should I do?

------

If this feature does not exist, could you add some feature to add, delete and rename those calendar?

**Comment by itchyny** [comment]
There should be a calendar list file at `~/.cache/calendar.vim/local/calendarList`. You can edit or delete the file.
