### ISSUE TITLE
Google Not allowing to create app name with 3 length charactor

### ISSUE THREAD

**Issue by kirubeltadesse** [itchyny/calendar.vim#230]
I created a project named `GCP1` because Google does not allow me to use a name that is three characters long. 

When I try to sync my calendar, it is not letting me do so.
<img width="585" alt="Screenshot 2024-04-23 at 8 05 01 AM" src="https://github.com/itchyny/calendar.vim/assets/6774894/ea630d7b-ed9a-45cd-b638-dd1c3d3c7239">

I was wondering if there is a workaround for this.

**Comment by itchyny** [comment]
I don't think this is not an issue of this plugin, so closing.

**Comment by itchyny** [comment]
I think this is not an issue of this plugin.
