### ISSUE TITLE
CalDAV support

### ISSUE THREAD

**Issue by kyrias** [itchyny/calendar.vim#43]
It would be nice to have CalDAV support so that you could host your calendar anywhere.

**Comment by protist** [comment]
I would also use definitely use this if it had CalDAV support. This would allow me to connect to my [OwnCloud](https://owncloud.org/) server. As a reference, another command-line calendar, [khal](https://github.com/pimutils/khal) syncs with CalDAV using [vdirsyncer](https://github.com/pimutils/vdirsyncer).

**Comment by DancingQuanta** [comment]
I would add that khal is indepedent of vdirsyncer as khal reads .ics files for calendar data while vdirsyncer syncs .ics files.
Do this calendar.vim reads .ics calendar files?

**Comment by paulrougieux** [comment]
[CALDAV](https://en.wikipedia.org/wiki/CalDAV) support is still discussed in #133 .
