### ISSUE TITLE
Event spread over two months does not show in events list

### ISSUE THREAD

**Issue by SuperFluffy** [itchyny/calendar.vim#47]
I have created an event starting on Oct 31 and ending on Nov 5. When I move the cursor to Oct 31 and toggle the events list, the event is not displayed (the event list on that date is empty). Here is the corresponding item entry from the cache file (which is stored in `2014/11/`).

```
{'id': '201407221433480005', 'summary': 'Random 4', 'end': {'date': '2014-11-6'}, 'start': {'date': '2014-10-31'}}
```

This behaviour seems to be reproducible by creating any event that is ending in a later month.

**Comment by joelstrouts** [comment]
I have just encountered this issue so it is not resolved. events spread over two months consistently do not appear in any view.
