### ISSUE TITLE
Integration with vimwiki

### ISSUE THREAD

**Issue by lervag** [itchyny/calendar.vim#49]
I just recently noticed your calendar plugin, and I am impressed. It looks amazing!

However, there is one major feature that I miss, and that is implemented in Matsumotos calendar plugin: A calendar action hook. This hook is used by [vimwiki](https://github.com/vimwiki/vimwiki) to let the function `vimwiki#diary#calendar_action` open the current chosen date with `<cr>`.

**Comment by thorlucas** [comment]
Has there been any update regarding this matter? I would love to be able to mark a day that has a diary entry.
