### ISSUE TITLE
Show full month name

### ISSUE THREAD

**Issue by petobens** [itchyny/calendar.vim#62]
Is it possible to show the full month name? Currently I see `Dec 2014` and I would like to have `December 2014`. Thanks again for such a great plugin!

**Comment by itchyny** [comment]
I implemented this feature.
Use the option
```vim
let g:calendar_date_full_month_name = 1
```
or from the argument
```vim
:Calendar -date_full_month_name
```

**Comment by petobens** [comment]
Great. Thank you very much!
