### ISSUE TITLE
Open a day in vim window/tab with the ability to paste and edit long text.

### ISSUE THREAD

**Issue by dtrckd** [itchyny/calendar.vim#65]
This would be an enhancement, that will be nice in calendar.vim. Is there any plan in this direction ?
Because it seems that the ihm is adapted for short text input....

**Comment by itchyny** [comment]
I do not get what you want to do... You mean you want to edit the events in a Vim buffer?

**Comment by dTracked** [comment]
Exactly. The event and task could be edited in a vim fashion way. Maybe this would be a new mode of editing. For example, one could open a buffer for a calendar day and simply paste a complex text and editing it, typing `:w' to save it. This text would be reachable for future view and modification in the calendar day previously chosen...

Does it make sense ?

**Comment by itchyny** [comment]
Sorry, closing due to low priority.
