### ISSUE TITLE
Support for repeating events?

### ISSUE THREAD

**Issue by firecat53** [itchyny/calendar.vim#69]
Planned support for repeating calendar events? 

Thanks! This is a great extension!!

**Comment by itchyny** [comment]
If you use this plugin with Google Calendar, you can create repeating events. Try starting block-visual mode with `<C-v>`. Select some days and press `i` to input the event title. You can use the block-visual mode within the month view for weekly events and in the days view for daily events. If you do not connect this plugin to Google Calendar, it is not supported.

**Comment by firecat53** [comment]
That's pretty cool! Did I miss it in the documentation someplace?

1. How about for non-standard repetitions (like every 3 days, for example?). 
2. If I delete one event from a repeating series does it delete just that event or the whole series?

Thanks!

**Comment by itchyny** [comment]
Hmm, it does not seem that it supports such a non-standard repetition because it will rarely used in our daily life. Also, deleting all the recurrence is impossible. I don't remember clearly but I think that it was the   limitation of the Google Calendar API.
