### ISSUE TITLE
Highlighting events, remapping movements, custom time intervals 

### ISSUE THREAD

**Issue by able16** [itchyny/calendar.vim#77]
Splitted issue with #78 and #79

~~I was wondering if gcal events can be colored by their event color instead of the calendar color.  
e.g. I have a calendar for my school schedule with individual events colored whereas Calendar.vim draws events to the Gcal color.~~

~~Also what option would have the bg of events filled instead of boxed?~~

As for remapping keys, instead of making changes in mapping.vim what would go in my .vimrc to remap `{h,j,k,l}`  to `{j,k,l,;}`?

~~Lastly I see that the time intervals of week/day view changes as per the window ratio. Is there a way to specifically set it so it always shows from 8am to midnight?~~

**Comment by itchyny** [comment]
Sorry but please split this issue into the individual problems...

**Comment by itchyny** [comment]
As for mappings, use the following settgins
```vim

augroup calendar-mappings
  autocmd!
  autocmd FileType calendar nmap j <Plug>(calendar_left)
  autocmd FileType calendar nmap k <Plug>(calendar_down)
  autocmd FileType calendar nmap l <Plug>(calendar_up)
  autocmd FileType calendar nmap ; <Plug>(calendar_right)
augroup END
```

**Comment by able16** [comment]
That works, thank you and splitted to multiple issues.
