### ISSUE TITLE
Color/highlighting invididual Gcal calendar events

### ISSUE THREAD

**Issue by able16** [itchyny/calendar.vim#78]
Splitting issue #77 

I was wondering if Gcal events can be colored by their event color instead of the calendar color (note screenshot).

e.g. I have a calendar for my school schedule with individual events colored whereas Calendar.vim draws events to the Gcal color.

Also what option would have the bg of events filled in (as you have in the readme) instead of boxed (note screenshot)

![](http://i.imgur.com/e107syP.png)

**Comment by itchyny** [comment]
It'll take time to implement this.

**Comment by itchyny** [comment]
In the dark colorscheme, using the calendar color as the bg color is not cool. So I decided to use the color for the fg color.
