### ISSUE TITLE
Can I display multiple google calendars?

### ISSUE THREAD

**Issue by Katsujp** [itchyny/calendar.vim#83]
Thank you very much for your useful calendar!

Currently, I am using multiple google calendars in one google account such as "Private schedule" and "Working schedule". Can I display multiple google calendars onto your calendar?

**Comment by itchyny** [comment]
Yes, you can. Are your both calendars enabled? Ensure to enable the both calendars on your web interface.

**Comment by Katsujp** [comment]
I found that I was not able to get my google calendar data even though I set google access token...
However I think this issue is affected by proxy environment.

I am sorry to bother you. I will re-check my settings.

**Comment by itchyny** [comment]
Fine.
