### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by michaelmior** [itchyny/calendar.vim#86]
There seems to be some sort of timezone issue because all of my events are offset by several hours.

**Comment by itchyny** [comment]
Please update to the latest version. That must be fixed.

**Comment by michaelmior** [comment]
I just installed yesterday and I checked and I am indeed running the latest version. Times are 8 hours off for me (both my calendar and my computer running vim are in EST/EDT).

**Comment by itchyny** [comment]
Please check the time string in `~/.cache/calendar.vim/google/event/{calendarstring}/2015/4/0`. Search by `/datetime`. Let me know the result of `:echo calendar#time#time_zone()`.

**Comment by michaelmior** [comment]
I have strings such as `'2015-04-02T14:30:00-04:00'`, which is correct. My time zone shows as `14400`. Instead of the event showing at 14:30, it shows at 22:30.

**Comment by itchyny** [comment]
My bad. I found a bug in my code. Thank you for reporting.

**Comment by michaelmior** [comment]
Thanks! This is working now :)

**Comment by petobens** [comment]
I have an event that starts at 10:00 (am) but the app shows that it starts at 13:00 . I checked the the time string and it says : `'dateTime': '2015-05-05T10:00:00-03:00'`.  The strange thing is that `:echo calendar#time#time_zone()` always returns `0`.

**Comment by itchyny** [comment]
@petobens Let me know the result of `:echo strftime('%z')`.

**Comment by petobens** [comment]
@itchyny,  `:echo strftime('%z')` returns `Argentina Standard Time`.

**Comment by itchyny** [comment]
That seems to be wired. The function `strftime` with the format `%z` should return the time offset from UTF in the format `[+-]hh:mm`. Please set the time_zone with the following configuration in vimrc.
```
let g:calendar_time_zone = '-03:00'
```

**Comment by petobens** [comment]
@itchyny thank you! That solves my problem.
