### ISSUE TITLE
week name show error

### ISSUE THREAD

**Issue by imbear** [itchyny/calendar.vim#87]
Chinese Win7 + Japanese local
![calendar - d__ - gvim -2015-05-13 10_41_51](https://cloud.githubusercontent.com/assets/2120811/7602936/aa0bce5c-f95d-11e4-8e5f-15011a541265.png)

**Comment by itchyny** [comment]
What does the following command show?
```vim
:echo map(range(3, 9), "strftime('%A', 60 * 60 * (24 * v:val + 10))")
```

**Comment by imbear** [comment]
:echo map(range(3, 9), "strftime('%A', 60 * 60 * (24 * v:val + 10))")
['ﾐﾇﾆﾚﾈﾕ', 'ﾐﾇﾆﾚﾒｻ', 'ﾐﾇﾆﾚｶ', 'ﾐﾇﾆﾚﾈ', 'ﾐﾇﾆﾚﾋﾄ', 'ﾐﾇﾆﾚﾎ・', 'ﾐﾇﾆﾚﾁ・']

**Comment by itchyny** [comment]
What is the result of the command? `:echo $LANG`

**Comment by imbear** [comment]
:echo $LANG
chinese_china

**Comment by itchyny** [comment]
Still I cannot get what happens on your PC and it'll too much for me to prepare the same environment. The following configuration sets the locale of the calendar to English.
```
let g:calendar_locale = 'en'
```

**Comment by imbear** [comment]
Thanks！
