### ISSUE TITLE
List or Agenda view

### ISSUE THREAD

**Issue by schmeisers** [itchyny/calendar.vim#88]
I would be great to have a list or agenda view.  I run calendar.vim in a small tmux pane and it would be very convenient to have a view that is a condensed list of upcoming events with their start and end times.

**Comment by foulowl** [comment]
This is an awesome idea. Would you consider bountysource for something like this?

**Comment by itchyny** [comment]
I implemented agenda view. You can enable by adding `agenda` to `g:calendar_views`.
```vim
let g:calendar_views = [ 'year', 'month', 'agenda', 'day_3', 'clock' ]
```
You can switch the views with `>`, `<` keys. You can also open the agenda view directly by the following command (after you have added `'agenda'` to `g:calendar_views`).
```vim
:Calendar -view=agenda
```

**Comment by schmeisers** [comment]
Awesome!  Thanks!
