### ISSUE TITLE
Can't delete task

### ISSUE THREAD

**Issue by foulowl** [itchyny/calendar.vim#89]
I can delete events with "D" or "dd", but the same does not appear to be true for tasks. Am I missing something obvious here or is there a bug?

Thank you!!

**Comment by itchyny** [comment]
D in the task list means you completed the task. Use L to clear the completed tasks.

**Comment by foulowl** [comment]
Is there no way to delete a task without marking it completed, then clearing the completed tasks? For example, I have added a task by mistake and would like to remove it, however I want to keep an archive of my completed tasks, so I don't ever want to press "L". Thank you!!

**Comment by itchyny** [comment]
Currently, no. Sorry.

**Comment by itchyny** [comment]
I implemented the feature.
You can enable by
```
let g:calendar_task_delete = 1
```
