### ISSUE TITLE
Events spanning days

### ISSUE THREAD

**Issue by trump6** [itchyny/calendar.vim#91]
Love the plugin, noticed a strange effect with an event spanning more than one day. Draws a three day event (3rd-5th) as two days. 
![screen shot 2015-06-19 at 4 23 51 pm](https://cloud.githubusercontent.com/assets/6811459/8262361/eaeaefa2-169f-11e5-9b88-61b4d436870a.png)
![screen shot 2015-06-19 at 4 22 13 pm](https://cloud.githubusercontent.com/assets/6811459/8262362/eddbd4ec-169f-11e5-8d1c-0221abe6beda.png)

**Comment by itchyny** [comment]
There might be inconsistency between the time zone settings. What is the result of `:strftime('%z')` and is that correct time zone offset for you?

**Comment by trump6** [comment]
Get `Not an editor command: strftime('%z')`, but `:echo strftime("%z")` gives -0400 which is correct.

**Comment by itchyny** [comment]
Uh, yes, my bad, that's what I indented to.

I need more information. How did you create the event? What do you expect it to be? Is that an event with the time range specified or not? What is the time zone setting of the calendar viewed on the Google Calendar web site (My Calendars → Calendar settings)?

**Comment by trump6** [comment]
No problem, event was created in google calendar, all day 7/3/2015-7/5/2015
(no time range) The time zone of the calendar is also GMT -04:00.
ᐧ

On Sat, Jun 20, 2015 at 12:01 PM, itchyny <notifications@github.com> wrote:

> Uh, yes, my bad, that's what I indented to.
>
> I need more information. How did you create the event? What do you expect
> it to be? Is that an event with the time range specified or not? What is
> the time zone setting of the calendar viewed on the Google Calendar web
> site (My Calendars → Calendar settings)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itchyny/calendar.vim/issues/91#issuecomment-113786516>
> .
>



-- 
Computer Science
Binghamton Scholars Program
914-826-7142

**Comment by itchyny** [comment]
Is the plugin updated to the HEAD? Please confirm with `git pull`.

**Comment by trump6** [comment]
Yes, up to date

**Comment by itchyny** [comment]
I want you to investigate the cache file. Please look into the file `~/.cache/calendar.vim/google/event/{calendarId}/yyyy/mm/0`. What does `start.dateTime` or `start.date` look like?

**Comment by trump6** [comment]
'start': {'date': '2015-07-03'}
'end': {'date': '2015-07-06'}

These are correct, but the calendar shows it as starting 07-02 and ending
07-05 (exclusive)
ᐧ

On Mon, Jun 22, 2015 at 10:42 AM, itchyny <notifications@github.com> wrote:

> I want you to investigate the cache file. Please look into the file
> ~/.cache/calendar.vim/google/event/{calendarId}/yyyy/mm/0. What does
> start.dateTime or start.date look like?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itchyny/calendar.vim/issues/91#issuecomment-114137026>
> .
>



-- 
Computer Science
Binghamton Scholars Program
914-826-7142

**Comment by itchyny** [comment]
I do not yet understand what causes the problem.

Please check if the following command shows the intended event.
```vim
:echo calendar#google#calendar#getEvents(2015, 7)['2015-7-3']
```
I'm grad if you paste the result with some confidential parts removed away (you may remove summary, organizer, creator, calendarId etc away).

**Comment by trump6** [comment]
That command gives the error
 `E716: Key not present in Dictionary: 2015-7-3
E15: Invalid expression: calendar#google#calendar#getEvents(2015, 7)['2015-7-3'] `

but changing it to `['2015-7-2']` gives

`{'events': [{'endtime': '20:00', 'endymd': [2015, 7, 4], 'summary': '___', 'endhms': [20, 0, 0], 'start': {'date': '2015-07-03'}, 'isTimeEvent': 0, 'status': 'confirmed',
 'reminders': {'useDefault': 0, 'overrides': [{'method': 'popup', 'minutes': 30}]}, 'id': '___', 'sequence': 0, 'organizer'
: {'email': 'trump6@gmail.com', 'displayName': 'Jack Fischer', 'self': 1}, 'isHoliday': 0, 'starttime': '20:00', 'iCalUID': '___', 'hms': [20, 0,
0], 'syntax': 'truc', 'isWeekNum': 0, 'calendarSummary': 'trump6@gmail.com', 'htmlLink': '___', 'isMoon': 0, 'kind': 'calendar#event', 'end': {'date': '2015-07-06'}, 'isDayNum': 0, 'etag': '"___"', 'creator': {'email': 'trump6@gmail.com', 'displayName': 'Jack Fischer', 'self': 1}, 'ymd': [2015, 7, 2], 'sec': 72000, 'created': '2015-06-07T18:53:28.000Z', 'calendarId': 'trump6@gmail.com', 'upd
ated': '2015-06-07T18:53:28.663Z'}, `...

**Comment by itchyny** [comment]
I fixed the problem. Please pull the repository and confirm.

**Comment by trump6** [comment]
Completely fixed! Thank you!
ᐧ

On Fri, Jun 26, 2015 at 9:02 PM, itchyny <notifications@github.com> wrote:

> I fixed the problem. Please pull the repository and confirm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itchyny/calendar.vim/issues/91#issuecomment-115930367>
> .
>



-- 
Computer Science
Binghamton Scholars Program
914-826-7142
