### ISSUE TITLE
Google calendars enabled

### ISSUE THREAD

**Issue by Miesco** [itchyny/calendar.vim#92]
Hi, how would I enable/disable a specific calendar on google calendars to be shown?  I can not see my events.

**Comment by itchyny** [comment]
Please enable the calendar on the website. (left sidebar)

The calendar list is cached for one day so please remove the time stamp files.
```
rm -rf ~/.cache/calendar.vim/timestamp/
```

**Comment by Miesco** [comment]
Thank you.  I have a feature suggestion.  To be able to refresh your calendar with <c-l>.  Basically <c-l> will `rm -rf ~/.cache/calendar.vim/timestamp/`, like

`autocmd Filetype calendar nmap <silent> <c-l> :!rm -rf ~/.cache/calendar.vim/timestamp/<cr><c-l>`

Except, perhaps, not as sketchy.

**Comment by itchyny** [comment]
Umm, I'll consider  implementing that feature later.
