### ISSUE TITLE
Background color due to `ErrorMsg`

### ISSUE THREAD

**Issue by NikosAlexandris** [itchyny/calendar.vim#98]
I have the following entry in `vimrc`:
```match ErrorMsg '\%>80v.\+'```. Runing `:Calendar` shows, as expected, all columns after character #80 with another background color (in my case it is red).  How do I solve this without disabling the above instruction?

**Comment by itchyny** [comment]
```vim
autocmd BufEnter,FileType *
      \   if &l:filetype ==# 'calendar'
      \ |   match
      \ | else
      \ |   match ErrorMsg '\%>80v.\+'
      \ | endif
```

**Comment by NikosAlexandris** [comment]
Awesome!
